[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-update-controller",
  "allow-update-secret",
  "allow-get-version",
  "allow-flush-fakeip",
  "allow-flush-dns",
  "allow-get-connections",
  "allow-close-all-connections",
  "allow-close-connections",
  "allow-get-groups",
  "allow-get-group-by-name",
  "allow-delay-group",
  "allow-get-proxy-providers",
  "allow-get-proxy-provider-by-name",
  "allow-update-proxy-provider",
  "allow-healthcheck-proxy-provider",
  "allow-healthcheck-node-in-provider",
  "allow-get-proxies",
  "allow-get-proxy-by-name",
  "allow-select-node-for-group",
  "allow-unfixed-proxy",
  "allow-delay-proxy-by-name",
  "allow-get-rules",
  "allow-get-rule-providers",
  "allow-update-rule-provider",
  "allow-get-base-config",
  "allow-reload-config",
  "allow-patch-base-config",
  "allow-update-geo",
  "allow-restart",
  "allow-upgrade-core",
  "allow-upgrade-ui",
  "allow-upgrade-geo",
  "allow-ws-traffic",
  "allow-ws-memory",
  "allow-ws-connections",
  "allow-ws-logs",
  "allow-ws-disconnect",
  "allow-clear-all-ws-connections",
]
