[package]
name = "mihomo_api"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.20", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["rt", "macros", "time"] }

[dev-dependencies]
