[package]
name = "clash-verge-types"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"

[dependencies]
serde = { workspace = true }
serde_yaml_ng = { workspace = true }
smartstring = { workspace = true }

[lints]
workspace = true
